### ISSUE TITLE
Using proguard

### ISSUE THREAD

**Issue by divyeshdesai** [achaiah/Enfomi#1]
I cant get proper tool for obfuscate my jar file...I am looking for open source tool...I have used PROGUARD but I cannot generate the obfuscated file..It is the same file after decompile...

**Comment by achaiah** [comment]
So what is your question?  This is the wrong project for obfuscation anyway. This project is about file encryption, not obfuscation.

**Comment by divyeshdesai** [comment]
well will it work for encryption of jar file for a java desktop application?
If yes than please tell me how can I encrypt it ?

**Comment by achaiah** [comment]
I don't understand the purpose of you trying to encrypt an application file. I mean, you can encrypt any file you want with this app (just follow the README) but you can't use that file until you decrypt it again.  If you're looking for something like PROGUARD then it's a totally different use case. PROGUARD doesn't encrypt anything.

**Comment by divyeshdesai** [comment]
Actually My problem is that I have made a java desktop application and I
want to make it irreversible so what can I do for it.
I have checked about it but only I got paid tools.But I want open source so
should me please suggest me or give some idea of it ?

**Comment by achaiah** [comment]
Sorry but that's not what encryption is for. To be honest you can never make something completely irreversible but obfuscation can make it harder. I'd say that unless you're making millions of dollars on your app it's not really worth the hassle, though.

If you're really insistent on it, there are probably some open source tools out there.  I publish my code for free, so obviously, I'm not concerned with making my app irreversible and am not up to speed about current obfuscation solutions.
