### ISSUE TITLE
Are there any binaries available?

### ISSUE THREAD

**Issue by mridah** [achaiah/Enfomi#2]
Hi, first of all thanks for making such a tool!! 
I couldn't find a way to contact you that's why added this in the issues

Do you have any binaries for this project ? Or maybe tell me what IDE can I use to directly compile this project

**Comment by achaiah** [comment]
Hi,

No problem. The entire project is in java so you don't have to have any special tools. To compile it you just have to have maven installed. If you prefer to work with gradle, you can use that instead, you just have to convert the pom.xml file into a gradle file.

If you prefer to use an IDE, you can use any that support java (e.g. Eclipse, IntelliJ etc). Those typically have maven already installed or have a plugin available that you can download.
